//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code wird erneut generiert. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Account
{


    public partial class OpenAuthProviders
    {

        /// <summary>
        /// providersList-Steuerelement.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView providersList;

    }
}
